apiVersion: v1
kind: Service
metadata:
  name: node-api-service
  namespace: default
  labels:
    app: node-api
    version: v1.0.0
spec:
  type: NodePort
  selector:
    app: node-api
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    nodePort: 30080
    protocol: TCP
